### PR TITLE
Added IdracFirmwareVersion and IdracHealth to idrac sysinfo

### PR DESCRIPTION
**Pull request by shubhrata-priya**

### CODE REVIEW

**Comment by jose-delarosa** [comment]
Thanks again

**Comment by shubhrata-priya** [comment]
Thanks @jose-delarosa for giving us this opportunity.

**Comment by jose-delarosa** [comment]
@shubhrata-priya, I think that [Status][Health| refers to the health of the server itself, not the health of the iDRAC. Can you please check? I already had this in the code.

**Comment by shubhrata-priya** [comment]
@jose-delarosa, [Status][Health] for idrac is fetching data from manager_uri(/redfish/v1/Managers/iDRAC.Embedded.1), while server health is fetching data from system_uri(/redfish/v1/Systems/System.Embedded.1).

**Comment by jose-delarosa** [comment]
@shubhrata-priya you are correct I missed that, thanks you.

**Pull request merged**
