### PR TITLE
firmware update 

### PR DESCRIPTION
**Pull request by prabhakarpujeri**
this set of patch contains firmware update  in following steps
step 1. download and extract  Catalog file from http://downloads.dell.com/catalog/Catalog.xml.gz
step 2. compare firmware inventory system and catalog file 
step 3. download firmware from http://downloads.dell.com
step 4.  upload all firmware for update
step 5. schedule job to update firmware

 
firmware update  feature available in 14th generation servers only

### CODE REVIEW

**Comment by jose-delarosa** [comment]
Thanks Prabhakar, this is great. I'm reviewing it. I'm assuming you've done required QA? Is this for 14G only?

**Comment by prabhakarpujeri** [comment]
Yes firmware update available only in 14g. I tested  with r940 and fc640.  I have observed update job scheduled but some time we receive status 503 (service not available) and suspecting idrac side issue

**Comment by jose-delarosa** [comment]
OK give me a few days to look at it. Thanks again.

**Comment by jose-delarosa** [comment]
Prabhakar,

I tested on two 14G servers and all firmware was updated successfully, though in one server I received an error while booting up about the firmware update failing (which required user intervention - press F1/F2), but it did not give me any details what the error was. After the server completed booting up, all firmware was updated successfully, so I'm not sure why I received an error.

Before merging, I have a few suggestions:

* add "run_once: true" when downloading and extracting the Catalog file and when creating
  the /tmp/firmware directory (we only need to do this once).
* in upload_firmware(), remove root/calvin (no hard-coding credentials!) and use send_post_request() instead to send POST request
* in compare_firmware(), remove code that has been commented out.
* the playbook should throw a message early on that it's only supported on 14G, which should
  then take that server out of the processing pool. In compare_firmware(), check
  for status_code=400, which means that resource is not available (schema not implemented).
* BONUS: server should be rebooted if firmware update requires it. How to tell?

**Comment by jose-delarosa** [comment]
Prabhakar,

The latest patch includes a lot of other minor changes not related to the firmware upgrade feature (mostly cosmetic updates which I agree make it easier to read, but can be done separately). In addition, I added functionality to delete users, which you patches removes.

Since the FW upgrade addition is fairly modular (1 playbook + 3 functions + a few extra lines of code), recommendation is to rebase the master branch and apply your patch against the latest master. I will hold off on making more updates to the master branch until your patched is merged.

Thank you.

**Comment by prabhakarpujeri** [comment]
i have created new pull request with suggested changes and we can close this pull request

**Pull request closed without merging**
